import { JournalEntry } from './types'

export const demoEntries: JournalEntry[] = [
  {
    id: '1',
    date: '2026-03-24',
    text: "Had a good morning today — made coffee and actually sat outside for a bit. Work was steady, nothing too stressful. Feeling pretty balanced overall.",
    score: 20,
    riskLevel: 'low',
    highlights: [],
    insight: "Language is calm and grounded, with present-tense engagement and positive sensory detail.",
    analyzedAt: '2026-03-24T09:00:00Z',
  },
  {
    id: '2',
    date: '2026-03-25',
    text: "Caught up with a friend over lunch, which was really nice. I've been trying to be more intentional about staying connected. The afternoon was productive.",
    score: 18,
    riskLevel: 'low',
    highlights: [
      { phrase: "staying connected", category: 'isolation', startIndex: 89, endIndex: 106 },
    ],
    insight: "Social engagement language is strong and forward-looking — a healthy linguistic pattern.",
    analyzedAt: '2026-03-25T09:00:00Z',
  },
  {
    id: '3',
    date: '2026-03-26',
    text: "Work meeting ran long but I handled it fine. Made dinner, watched something good. I feel okay — not amazing, but okay.",
    score: 22,
    riskLevel: 'low',
    highlights: [],
    insight: "Neutral, stable tone with self-regulation language present.",
    analyzedAt: '2026-03-26T09:00:00Z',
  },
  {
    id: '4',
    date: '2026-03-27',
    text: "Felt a little off today, hard to explain. Got through everything I needed to do. I keep thinking I should reach out to people more but I just never do.",
    score: 28,
    riskLevel: 'low',
    highlights: [
      { phrase: "I keep thinking", category: 'self-focus', startIndex: 67, endIndex: 82 },
      { phrase: "I just never do", category: 'isolation', startIndex: 133, endIndex: 148 },
    ],
    insight: "Mild self-critical loop beginning to appear, with a small avoidance pattern in social language.",
    analyzedAt: '2026-03-27T09:00:00Z',
  },
  {
    id: '5',
    date: '2026-03-28',
    text: "Couldn't really focus today. I've been putting off a lot of things and I'm not sure why. It's like the motivation just isn't there anymore.",
    score: 36,
    riskLevel: 'low',
    highlights: [
      { phrase: "motivation just isn't there anymore", category: 'hopelessness', startIndex: 103, endIndex: 137 },
      { phrase: "putting off a lot", category: 'self-focus', startIndex: 47, endIndex: 64 },
    ],
    insight: "First signs of motivational language loss and vague hopelessness emerging in the text.",
    analyzedAt: '2026-03-28T09:00:00Z',
  },
  {
    id: '6',
    date: '2026-03-29',
    text: "I canceled plans again tonight. I told myself I'd feel better staying in, but I didn't really. I've been spending a lot of time alone and it's starting to feel normal.",
    score: 44,
    riskLevel: 'medium',
    highlights: [
      { phrase: "canceled plans again", category: 'isolation', startIndex: 2, endIndex: 22 },
      { phrase: "I've been spending a lot of time alone", category: 'isolation', startIndex: 87, endIndex: 124 },
      { phrase: "starting to feel normal", category: 'hopelessness', startIndex: 141, endIndex: 164 },
    ],
    insight: "Isolation behavior is appearing in language alongside normalization of withdrawal — a notable shift.",
    analyzedAt: '2026-03-29T09:00:00Z',
  },
  {
    id: '7',
    date: '2026-03-30',
    text: "I don't really know what I want lately. Everything feels kind of heavy. I keep replaying conversations in my head and wondering if I said something wrong.",
    score: 49,
    riskLevel: 'medium',
    highlights: [
      { phrase: "don't really know what I want", category: 'hopelessness', startIndex: 2, endIndex: 30 },
      { phrase: "everything feels kind of heavy", category: 'negative-emotion', startIndex: 39, endIndex: 68 },
      { phrase: "I keep replaying", category: 'self-focus', startIndex: 70, endIndex: 86 },
    ],
    insight: "Rumination language is increasing alongside vague emotional heaviness and uncertainty.",
    analyzedAt: '2026-03-30T09:00:00Z',
  },
  {
    id: '8',
    date: '2026-03-31',
    text: "Stayed in all day. I meant to do things but I just couldn't bring myself to start. I feel like I'm just going through the motions most of the time.",
    score: 55,
    riskLevel: 'medium',
    highlights: [
      { phrase: "just couldn't bring myself", category: 'negative-emotion', startIndex: 49, endIndex: 74 },
      { phrase: "I feel like I'm", category: 'self-focus', startIndex: 82, endIndex: 97 },
      { phrase: "going through the motions", category: 'hopelessness', startIndex: 101, endIndex: 126 },
    ],
    insight: "Dissociation and emotional inertia language is growing — 'going through the motions' is a strong marker.",
    analyzedAt: '2026-03-31T09:00:00Z',
  },
  {
    id: '9',
    date: '2026-04-01',
    text: "I snapped at someone today and immediately felt terrible about it. I think I'm just tired. I've been avoiding my phone — there are messages I haven't replied to in days.",
    score: 58,
    riskLevel: 'medium',
    highlights: [
      { phrase: "felt terrible about it", category: 'negative-emotion', startIndex: 44, endIndex: 66 },
      { phrase: "avoiding my phone", category: 'isolation', startIndex: 97, endIndex: 114 },
      { phrase: "messages I haven't replied to", category: 'isolation', startIndex: 130, endIndex: 158 },
    ],
    insight: "Social withdrawal is now behavioral as well as linguistic — avoidance language is prominent.",
    analyzedAt: '2026-04-01T09:00:00Z',
  },
  {
    id: '10',
    date: '2026-04-02',
    text: "I woke up and just stared at the ceiling for a while. I don't see the point in most things right now. Everything feels like too much effort and not enough reward.",
    score: 63,
    riskLevel: 'medium',
    highlights: [
      { phrase: "don't see the point", category: 'hopelessness', startIndex: 54, endIndex: 73 },
      { phrase: "everything feels like too much effort", category: 'negative-emotion', startIndex: 96, endIndex: 132 },
      { phrase: "not enough reward", category: 'hopelessness', startIndex: 137, endIndex: 154 },
    ],
    insight: "Clear anhedonia language is present — 'don't see the point' combined with effort-reward imbalance is a significant marker.",
    analyzedAt: '2026-04-02T09:00:00Z',
  },
  {
    id: '11',
    date: '2026-04-03',
    text: "Nobody really checks in on me and I know that's partly my fault. I've been pulling away. I just feel like I'm a burden when I reach out, so I don't.",
    score: 69,
    riskLevel: 'high',
    highlights: [
      { phrase: "nobody really checks in on me", category: 'isolation', startIndex: 0, endIndex: 28 },
      { phrase: "I've been pulling away", category: 'isolation', startIndex: 63, endIndex: 84 },
      { phrase: "I'm a burden", category: 'hopelessness', startIndex: 107, endIndex: 119 },
      { phrase: "so I don't", category: 'self-focus', startIndex: 138, endIndex: 148 },
    ],
    insight: "Burden-perception language is a strong depression marker — combined with self-blamed isolation, this is a high-risk linguistic pattern.",
    analyzedAt: '2026-04-03T09:00:00Z',
  },
  {
    id: '12',
    date: '2026-04-04',
    text: "I keep thinking about how things used to feel different. I miss feeling excited about stuff. Now it all just feels flat. I don't think I'm okay.",
    score: 73,
    riskLevel: 'high',
    highlights: [
      { phrase: "I keep thinking", category: 'self-focus', startIndex: 0, endIndex: 15 },
      { phrase: "miss feeling excited", category: 'negative-emotion', startIndex: 59, endIndex: 79 },
      { phrase: "all just feels flat", category: 'hopelessness', startIndex: 94, endIndex: 113 },
      { phrase: "I don't think I'm okay", category: 'negative-emotion', startIndex: 115, endIndex: 137 },
    ],
    insight: "Retrospective loss language paired with flat affect and explicit self-assessment of not being okay — a dense cluster of high-risk markers.",
    analyzedAt: '2026-04-04T09:00:00Z',
  },
  {
    id: '13',
    date: '2026-04-05',
    text: "I barely left my room today. I told myself I'd try to go outside but I couldn't. I feel invisible. Like even if I disappeared, it would take a while for anyone to notice.",
    score: 76,
    riskLevel: 'high',
    highlights: [
      { phrase: "barely left my room", category: 'isolation', startIndex: 2, endIndex: 21 },
      { phrase: "I feel invisible", category: 'hopelessness', startIndex: 80, endIndex: 96 },
      { phrase: "if I disappeared", category: 'hopelessness', startIndex: 107, endIndex: 123 },
      { phrase: "take a while for anyone to notice", category: 'isolation', startIndex: 135, endIndex: 167 },
    ],
    insight: "Invisibility language and disappearance ideation are critical markers — this entry shows a significant escalation in hopelessness.",
    analyzedAt: '2026-04-05T09:00:00Z',
  },
  {
    id: '14',
    date: '2026-04-06',
    text: "I don't know what the point is anymore. I've been in my room all week and I keep canceling plans. I just feel like I'm watching everyone else live their lives.",
    score: 78,
    riskLevel: 'high',
    highlights: [
      { phrase: "don't know what the point is", category: 'hopelessness', startIndex: 2, endIndex: 29 },
      { phrase: "in my room all week", category: 'isolation', startIndex: 58, endIndex: 77 },
      { phrase: "I just feel like I'm", category: 'self-focus', startIndex: 107, endIndex: 127 },
    ],
    insight: "Language shows strong isolation and hopelessness markers — a pattern that has intensified over the past week.",
    analyzedAt: '2026-04-06T09:00:00Z',
  },
]
